### ISSUE TITLE
Strange compilation error on CI with backtrace-rs crate due to cfg-if

### ISSUE THREAD

**Issue by bcortier-devolutions** [alexcrichton/cfg-if#33]
Hi!

We had a strange compilation error in our CI related to cfg-if  following last backtrace-rs update. The error was introduced by commit https://github.com/rust-lang/backtrace-rs/commit/7a1d3573f6b319bf8d3d1b3791cde80bd2ccc768.

```
   Compiling backtrace v0.3.42 (https://github.com/Devolutions/backtrace-rs?branch=test#46961d32)
error: target pointer width detected: 64
  --> C:\Users\ContainerAdministrator\.cargo\git\checkouts\backtrace-rs-ac5effeeee72e05a\46961d3\src\backtrace\dbghelp.rs:25:1
   |
25 | compile_error!("target pointer width detected: 64");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: expected an item keyword
   --> C:\Users\ContainerAdministrator\.cargo\git\checkouts\backtrace-rs-ac5effeeee72e05a\46961d3\src\backtrace\dbghelp.rs:126:13
    |
126 |             let function_table_access = dbghelp.SymFunctionTableAccess64();
    |             ^^^

error: aborting due to 2 previous errors

error: could not compile `backtrace`.
```

The first error was produced by myself with following code:
```rust
#[cfg(target_pointer_width = "64")]
compile_error!("target pointer width detected: 64");
```
showing target_pointer_width is indeed 64.

The build is performed on a Windows x86_64 build container on Microsoft Azure Pipeline but doesn't arise in our other pipelines with similar setup. We can't reproduce it locally on 32 bits and 64 bits targets either.

We managed to build by removing cfg-if usage and writing what I suppose to be the cfg-if generated code by hand:  https://github.com/Devolutions/backtrace-rs/commit/9f2328e088fee94011c3f99c83c763bf2f8747b1

This is very strange because the error occurs in only one pipeline and can be prevented by not using cfg-if. This is really mysterious to us. Do you have any idea?

Thank you!

**Comment by alexcrichton** [comment]
Oh dear this does indeed sound weird. One thing I'm remembering now though is I forgot to update the dependency on `cfg-if`, if you do `cargo update -p cfg-if`, does it fix the issue for you?

Otherwise, do you know where the `compile_error!("target pointer width detected: 64");` code comes from? I don't see that in this crate...

**Comment by bcortier-devolutions** [comment]
Okay I tried to update cfg-if but I can't get cargo to use my patched version then (probably one of the dependency has a hard requirement on cfg-if prior to 0.3.10 ?).

Here is the output I got trying to update:
```
warning: Patch `backtrace v0.3.42 (https://github.com/Devolutions/backtrace-rs?branch=test#6c56082e)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
      Adding backtrace v0.3.41
      Adding backtrace-sys v0.1.32
```

It reverted back to previous backtrace version ignoring our patch.

> Otherwise, do you know where the compile_error!("target pointer width detected: 64"); code comes from? I don't see that in this crate...

Yes, as mentioned above I added that error myself to make sure the error wasn't simply caused in conditionally generated code only, this isn't in the original codebase. Maybe it wasn't relevant to include, sorry :sweat_smile:

**Comment by alexcrichton** [comment]
Hm I've [pushed up a comment](https://github.com/rust-lang/backtrace-rs/commit/691262454ae6355bb37af9087e51be7c61c957c7) for the `backtrace` crate which may help? It looks like weirdness is likely going on with the cfg-if version perhaps, but can you try with that and see if it helps?

If it doesn't, do you know what version of `cfg-if` is being used?

**Comment by bcortier-devolutions** [comment]
In fact, that's what I tried that just before using [this commit](https://github.com/Devolutions/backtrace-rs/commit/6c56082e46832612ec7db5c5d6004d181977815c).
From what I can read in the Cargo.lock it always pick `0.1.9`.

**Comment by alexcrichton** [comment]
Ok I believe that's the bug in that case, the `backtrace` crate needs 0.1.10 to compile correctly. I think there may be something else going wrong if you've applied the patch yourself but `cfg-if` 0.1.9 is still in use.
